// <auto-generated />
namespace Product.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class qqq12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qqq12));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111357189_qqq12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
